#!/bin/sh -
AXIOMEDITOR='emacsclient +$line $name >/dev/null 2>&1'
export AXIOMEDITOR
FRICASCMD='/usr/local/lib/fricas/target/x86_64-linux-gnu/bin/fricas'
export FRICASCMD
if which emacs; then
  emacs --eval '(progn (server-start) (setq load-path (cons (quote "/usr/local/lib/fricas/emacs") load-path)) (setq auto-mode-alist (cons (quote ("\\.fri$" . fricas-mode)) auto-mode-alist)) (require (quote fricas)))' -f fricas $@;
else 
  echo You must have installed emacs to run efricas.;
fi
